name: Build and deploy static HTML to Dev Slot

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App (Dev Slot)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kodeklouddemo'
          slot-name: 'dev'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEV_SLOT }}