name: Build and deploy static HTML to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kodeklouddemo'
          slot-name: 'Production'
          package: . 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7928333CB97A4C539316E405B46DA429 }}
