name: Build and deploy static HTML to Azure Web App

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kodeklouddemo'
          # Aqui está o segredo: Se for a branch main, vai para Production. 
          # Se não, vai para o slot 'dev'.
          slot-name: ${{ github.ref == 'refs/heads/main' && 'Production' || 'dev' }}
          package: .
          # Importante: O slot 'dev' geralmente precisa de um Publish Profile próprio
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}